"""Revison posterior al MVP

Revision ID: 0146ff2b9e69
Revises: f4f083c1d0fc
Create Date: 2025-11-20 01:26:26.793310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0146ff2b9e69'
down_revision: Union[str, Sequence[str], None] = 'f4f083c1d0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_attempt_id_fkey'), 'answers', type_='foreignkey')
    op.drop_constraint(op.f('answers_question_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'answers', 'quiz_attempts', ['attempt_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('questions_quiz_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('quizzes_summary_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('summaries_user_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('summary_documents_summary_id_fkey'), 'summary_documents', type_='foreignkey')
    op.drop_constraint(op.f('summary_documents_document_id_fkey'), 'summary_documents', type_='foreignkey')
    op.create_foreign_key(None, 'summary_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'summary_documents', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summary_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'summary_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summary_documents_document_id_fkey'), 'summary_documents', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('summary_documents_summary_id_fkey'), 'summary_documents', 'summaries', ['summary_id'], ['id'])
    op.drop_constraint(None, 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_user_id_fkey'), 'summaries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quizzes_summary_id_fkey'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'questions', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('questions_quiz_id_fkey'), 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'answers', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'answers', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('answers_question_id_fkey'), 'answers', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('answers_attempt_id_fkey'), 'answers', 'quiz_attempts', ['attempt_id'], ['id'])
    # ### end Alembic commands ###
