"""Update models to Mapped[] style with denormalization

Revision ID: 1e432b42e2f8
Revises: 0bc4a983fb88
Create Date: 2025-11-28 15:18:43.031656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e432b42e2f8'
down_revision: Union[str, Sequence[str], None] = '0bc4a983fb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('quiz_attempts', sa.Column('quiz_title', sa.String(length=255), nullable=False))
    op.add_column('quiz_attempts', sa.Column('quiz_state', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('quizzes', sa.Column('summary_id', sa.UUID(), nullable=True))
    op.add_column('quizzes', sa.Column('source_summary_title', sa.String(length=255), nullable=True))
    op.add_column('quizzes', sa.Column('source_document_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quizzes', sa.Column('source_study_space_name', sa.String(length=100), nullable=True))
    op.add_column('quizzes', sa.Column('source_study_space_color', sa.String(length=7), nullable=True))
    op.alter_column('quizzes', 'study_space_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_studyforge_quizzes_source_document_id'), table_name='quizzes')
    op.drop_index(op.f('ix_studyforge_quizzes_source_summary_id'), table_name='quizzes')
    op.create_index(op.f('ix_studyforge_quizzes_summary_id'), 'quizzes', ['summary_id'], unique=False, schema='studyforge')
    op.drop_constraint(op.f('fk_quizzes_source_summary_id_summaries'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_source_document_id_documents'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_column('quizzes', 'source_names')
    op.drop_column('quizzes', 'source_metadata')
    op.drop_column('quizzes', 'source_document_id')
    op.drop_column('quizzes', 'source_summary_id')
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_study_space_summaries_study_space_id_study_spaces'), 'study_space_summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_summaries_summary_id_summaries'), 'study_space_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_summaries_study_space_id_study_spaces'), 'study_space_summaries', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_study_space_summaries_summary_id_summaries'), 'study_space_summaries', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('summaries', sa.Column('document_title', sa.String(length=255), nullable=False))
    op.add_column('summaries', sa.Column('document_file_name', sa.String(length=255), nullable=False))
    op.add_column('summaries', sa.Column('study_space_name', sa.String(length=100), nullable=False))
    op.add_column('summaries', sa.Column('study_space_color', sa.String(length=7), nullable=False))
    op.alter_column('summaries', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('summaries', 'document_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_column('summaries', 'source_document_filename')
    op.drop_column('summaries', 'source_document_title')
    op.drop_constraint(op.f('fk_summary_documents_document_id_documents'), 'summary_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_summary_documents_summary_id_summaries'), 'summary_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summary_documents_summary_id_summaries'), 'summary_documents', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_summary_documents_document_id_documents'), 'summary_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_summary_documents_document_id_documents'), 'summary_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summary_documents_summary_id_summaries'), 'summary_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summary_documents_summary_id_summaries'), 'summary_documents', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('fk_summary_documents_document_id_documents'), 'summary_documents', 'documents', ['document_id'], ['id'])
    op.add_column('summaries', sa.Column('source_document_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('summaries', sa.Column('source_document_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'], ondelete='CASCADE')
    op.alter_column('summaries', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('summaries', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('summaries', 'document_state',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('summaries', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('summaries', 'study_space_color')
    op.drop_column('summaries', 'study_space_name')
    op.drop_column('summaries', 'document_file_name')
    op.drop_column('summaries', 'document_title')
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_study_space_summaries_summary_id_summaries'), 'study_space_summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_summaries_study_space_id_study_spaces'), 'study_space_summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_summaries_summary_id_summaries'), 'study_space_summaries', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('fk_study_space_summaries_study_space_id_study_spaces'), 'study_space_summaries', 'study_spaces', ['study_space_id'], ['id'])
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'])
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'])
    op.add_column('quizzes', sa.Column('source_summary_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('source_document_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('source_names', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_source_document_id_documents'), 'quizzes', 'documents', ['source_document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_quizzes_source_summary_id_summaries'), 'quizzes', 'summaries', ['source_summary_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_studyforge_quizzes_summary_id'), table_name='quizzes', schema='studyforge')
    op.create_index(op.f('ix_studyforge_quizzes_source_summary_id'), 'quizzes', ['source_summary_id'], unique=False)
    op.create_index(op.f('ix_studyforge_quizzes_source_document_id'), 'quizzes', ['source_document_id'], unique=False)
    op.alter_column('quizzes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('quizzes', 'study_space_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('quizzes', 'source_study_space_color')
    op.drop_column('quizzes', 'source_study_space_name')
    op.drop_column('quizzes', 'source_document_titles')
    op.drop_column('quizzes', 'source_summary_title')
    op.drop_column('quizzes', 'summary_id')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('quiz_attempts', 'quiz_state')
    op.drop_column('quiz_attempts', 'quiz_title')
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
