"""restructure_quiz_table_to_plan_spec

Revision ID: 291c926facbd
Revises: da3f1a1fb344
Create Date: 2025-11-28 20:25:18.098107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '291c926facbd'
down_revision: Union[str, Sequence[str], None] = 'da3f1a1fb344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('quizzes', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.add_column('quizzes', sa.Column('source_summary_id', sa.UUID(), nullable=True))
    op.add_column('quizzes', sa.Column('source_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quizzes', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('quizzes', 'study_space_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_studyforge_quizzes_summary_id'), table_name='quizzes')
    op.create_index(op.f('ix_studyforge_quizzes_source_document_id'), 'quizzes', ['source_document_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_quizzes_source_summary_id'), 'quizzes', ['source_summary_id'], unique=False, schema='studyforge')
    op.drop_constraint(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_quizzes_source_summary_id_summaries'), 'quizzes', 'summaries', ['source_summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quizzes_source_document_id_documents'), 'quizzes', 'documents', ['source_document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='SET NULL')
    op.drop_column('quizzes', 'summary_id')
    op.drop_column('quizzes', 'source_summary_title')
    op.drop_column('quizzes', 'source_study_space_name')
    op.drop_column('quizzes', 'source_study_space_color')
    op.drop_column('quizzes', 'source_document_titles')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'])
    op.add_column('quizzes', sa.Column('source_document_titles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('source_study_space_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('source_study_space_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('source_summary_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('summary_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_quizzes_source_document_id_documents'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_source_summary_id_summaries'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.drop_index(op.f('ix_studyforge_quizzes_source_summary_id'), table_name='quizzes', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quizzes_source_document_id'), table_name='quizzes', schema='studyforge')
    op.create_index(op.f('ix_studyforge_quizzes_summary_id'), 'quizzes', ['summary_id'], unique=False)
    op.alter_column('quizzes', 'study_space_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('quizzes', 'source_metadata')
    op.drop_column('quizzes', 'source_names')
    op.drop_column('quizzes', 'source_summary_id')
    op.drop_column('quizzes', 'source_document_id')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
