"""Add study spaces with many-to-many relationships

Revision ID: 2ab36b97654b
Revises: 3ae7abe08bf7
Create Date: 2025-11-25 23:14:59.926067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab36b97654b'
down_revision: Union[str, Sequence[str], None] = '3ae7abe08bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_study_spaces_user_id'), 'study_spaces', ['user_id'], unique=False, schema='studyforge')
    op.create_table('study_space_documents',
    sa.Column('study_space_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['studyforge.documents.id'], ),
    sa.ForeignKeyConstraint(['study_space_id'], ['studyforge.study_spaces.id'], ),
    sa.PrimaryKeyConstraint('study_space_id', 'document_id'),
    schema='studyforge'
    )
    op.create_table('study_space_summaries',
    sa.Column('study_space_id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['study_space_id'], ['studyforge.study_spaces.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['studyforge.summaries.id'], ),
    sa.PrimaryKeyConstraint('study_space_id', 'summary_id'),
    schema='studyforge'
    )
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('quizzes', sa.Column('study_space_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_studyforge_quizzes_study_space_id'), 'quizzes', ['study_space_id'], unique=False, schema='studyforge')
    op.drop_constraint(op.f('quizzes_summary_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quizzes', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('summaries_user_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('summary_documents_document_id_fkey'), 'summary_documents', type_='foreignkey')
    op.drop_constraint(op.f('summary_documents_summary_id_fkey'), 'summary_documents', type_='foreignkey')
    op.create_foreign_key(None, 'summary_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'summary_documents', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summary_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'summary_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summary_documents_summary_id_fkey'), 'summary_documents', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('summary_documents_document_id_fkey'), 'summary_documents', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_user_id_fkey'), 'summaries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quizzes_summary_id_fkey'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.drop_index(op.f('ix_studyforge_quizzes_study_space_id'), table_name='quizzes', schema='studyforge')
    op.drop_column('quizzes', 'study_space_id')
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.drop_table('study_space_summaries', schema='studyforge')
    op.drop_table('study_space_documents', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_study_spaces_user_id'), table_name='study_spaces', schema='studyforge')
    op.drop_table('study_spaces', schema='studyforge')
    # ### end Alembic commands ###
