"""baseline: users, documents, summaries, quizzes

Revision ID: 37f7c983b414
Revises: 
Create Date: 2025-10-06 10:18:14.723987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37f7c983b414'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_users_email'), 'users', ['email'], unique=True, schema='studyforge')
    op.create_index(op.f('ix_studyforge_users_id'), 'users', ['id'], unique=False, schema='studyforge')
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['studyforge.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['studyforge.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.drop_table('alembic_version')
    op.add_column('documents', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('documents', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_studyforge_documents_id'), 'documents', ['id'], unique=False, schema='studyforge')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', schema='studyforge', type_='foreignkey')
    op.drop_index(op.f('ix_studyforge_documents_id'), table_name='documents', schema='studyforge')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('documents', 'description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('documents', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'user_id')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('summaries', schema='studyforge')
    op.drop_table('quizzes', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_users_id'), table_name='users', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_users_email'), table_name='users', schema='studyforge')
    op.drop_table('users', schema='studyforge')
    # ### end Alembic commands ###
