"""Redesign quizzes to use JSON structure

Revision ID: 3ae7abe08bf7
Revises: 0146ff2b9e69
Create Date: 2025-11-20 04:41:39.234891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ae7abe08bf7'
down_revision: Union[str, Sequence[str], None] = '0146ff2b9e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studyforge_answers_attempt_id'), table_name='answers')
    op.drop_index(op.f('ix_studyforge_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_studyforge_questions_quiz_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('quiz_attempts', sa.Column('correct_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('quiz_attempts', sa.Column('user_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_constraint(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('quizzes', sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_summary_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_column('quizzes', 'max_questions')
    op.drop_constraint(op.f('summaries_user_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('summary_documents_document_id_fkey'), 'summary_documents', type_='foreignkey')
    op.drop_constraint(op.f('summary_documents_summary_id_fkey'), 'summary_documents', type_='foreignkey')
    op.create_foreign_key(None, 'summary_documents', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'summary_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summary_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'summary_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summary_documents_summary_id_fkey'), 'summary_documents', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('summary_documents_document_id_fkey'), 'summary_documents', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_user_id_fkey'), 'summaries', 'users', ['user_id'], ['id'])
    op.add_column('quizzes', sa.Column('max_questions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_summary_id_fkey'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'])
    op.drop_column('quizzes', 'questions')
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('quiz_attempts', 'user_answers')
    op.drop_column('quiz_attempts', 'correct_answers')
    op.drop_constraint(None, 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.create_table('questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('option_b', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('option_c', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('option_d', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('correct_option', postgresql.ENUM('A', 'B', 'C', 'D', name='optionenum'), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='questions_quiz_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_studyforge_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selected_option', postgresql.ENUM('A', 'B', 'C', 'D', name='optionenum'), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], name=op.f('answers_attempt_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('answers_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('answers_pkey'))
    )
    op.create_index(op.f('ix_studyforge_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_studyforge_answers_attempt_id'), 'answers', ['attempt_id'], unique=False)
    # ### end Alembic commands ###
