"""create missing tables (users/summaries/quizzes)

Revision ID: 458a31d5300e
Revises: 37f7c983b414
Create Date: 2025-10-06 12:29:33.636865
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "458a31d5300e"
down_revision: Union[str, Sequence[str], None] = "37f7c983b414"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###

    # users
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("password_hash", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="studyforge",
    )
    op.create_index(
        op.f("ix_studyforge_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="studyforge",
    )
    op.create_index(
        op.f("ix_studyforge_users_id"),
        "users",
        ["id"],
        unique=False,
        schema="studyforge",
    )

    # quizzes
    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["studyforge.documents.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="studyforge",
    )

    # summaries
    op.create_table(
        "summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["studyforge.documents.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="studyforge",
    )

    # ❌ NUNCA tocar la tabla de versiones de Alembic
    # op.drop_table('alembic_version')  # ← Eliminado

    # documents: columnas nuevas y cambios de tipo/default
    op.add_column(
        "documents",
        sa.Column("user_id", sa.Integer(), nullable=True),
        schema="studyforge",
    )
    op.add_column(
        "documents",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        schema="studyforge",
    )
    op.alter_column(
        "documents",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=200),
        existing_nullable=False,
        schema="studyforge",
    )
    op.alter_column(
        "documents",
        "description",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=300),
        existing_nullable=True,
        schema="studyforge",
    )
    op.alter_column(
        "documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=True,
        schema="studyforge",
    )
    op.create_index(
        op.f("ix_studyforge_documents_id"),
        "documents",
        ["id"],
        unique=False,
        schema="studyforge",
    )
    op.create_foreign_key(
        None,
        "documents",
        "users",
        ["user_id"],
        ["id"],
        source_schema="studyforge",
        referent_schema="studyforge",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###

    # FK e índice de documents
    op.drop_constraint(None, "documents", schema="studyforge", type_="foreignkey")
    op.drop_index(op.f("ix_studyforge_documents_id"), table_name="documents", schema="studyforge")

    # revertir cambios en documents
    op.alter_column(
        "documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
        schema="studyforge",
    )
    op.alter_column(
        "documents",
        "description",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
        schema="studyforge",
    )
    op.alter_column(
        "documents",
        "title",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        schema="studyforge",
    )
    op.drop_column("documents", "updated_at", schema="studyforge")
    op.drop_column("documents", "user_id", schema="studyforge")

    # ❌ No tocar alembic_version en downgrade tampoco
    # op.create_table('alembic_version', ...)  # ← Eliminado

    # drop nuevas tablas
    op.drop_table("summaries", schema="studyforge")
    op.drop_table("quizzes", schema="studyforge")
    op.drop_index(op.f("ix_studyforge_users_id"), table_name="users", schema="studyforge")
    op.drop_index(op.f("ix_studyforge_users_email"), table_name="users", schema="studyforge")
    op.drop_table("users", schema="studyforge")
    # ### end Alembic commands ###
