"""add_cascade_to_quiz_attempt_quiz_id

Revision ID: c7764155e86b
Revises: 291c926facbd
Create Date: 2025-11-28 20:26:38.168285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7764155e86b'
down_revision: Union[str, Sequence[str], None] = '291c926facbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_quizzes_source_summary_id_summaries'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_source_document_id_documents'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quizzes_source_summary_id_summaries'), 'quizzes', 'summaries', ['source_summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quizzes_source_document_id_documents'), 'quizzes', 'documents', ['source_document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'])
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_source_document_id_documents'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_source_summary_id_summaries'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_quizzes_source_document_id_documents'), 'quizzes', 'documents', ['source_document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_quizzes_source_summary_id_summaries'), 'quizzes', 'summaries', ['source_summary_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
