"""Add denormalized fields for deletion tracking and cascade configuration

Revision ID: c9fc36cea810
Revises: 2ab36b97654b
Create Date: 2025-11-26 16:03:50.884408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9fc36cea810'
down_revision: Union[str, Sequence[str], None] = '2ab36b97654b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key('fk_documents_user_id', 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('quiz_attempts', sa.Column('quiz_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quiz_attempts', sa.Column('study_space_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key('fk_quiz_attempts_quiz_id', 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key('fk_quiz_attempts_user_id', 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('quizzes', sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quizzes', sa.Column('source_summary_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_summary_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_study_space_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key('fk_quizzes_user_id', 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key('fk_quizzes_summary_id', 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key('fk_quizzes_study_space_id', 'quizzes', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    op.drop_constraint(op.f('study_space_documents_study_space_id_fkey'), 'study_space_documents', type_='foreignkey')
    op.drop_constraint(op.f('study_space_documents_document_id_fkey'), 'study_space_documents', type_='foreignkey')
    op.create_foreign_key('fk_study_space_documents_study_space_id', 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    op.create_foreign_key('fk_study_space_documents_document_id', 'study_space_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('study_space_summaries_study_space_id_fkey'), 'study_space_summaries', type_='foreignkey')
    op.drop_constraint(op.f('study_space_summaries_summary_id_fkey'), 'study_space_summaries', type_='foreignkey')
    op.create_foreign_key('fk_study_space_summaries_summary_id', 'study_space_summaries', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key('fk_study_space_summaries_study_space_id', 'study_space_summaries', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    op.drop_constraint(op.f('study_spaces_user_id_fkey'), 'study_spaces', type_='foreignkey')
    op.create_foreign_key('fk_study_spaces_user_id', 'study_spaces', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('summaries', sa.Column('deleted_documents_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('summaries_user_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key('fk_summaries_user_id', 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('summary_documents_document_id_fkey'), 'summary_documents', type_='foreignkey')
    op.drop_constraint(op.f('summary_documents_summary_id_fkey'), 'summary_documents', type_='foreignkey')
    op.create_foreign_key('fk_summary_documents_summary_id', 'summary_documents', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key('fk_summary_documents_document_id', 'summary_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_summary_documents_document_id', 'summary_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint('fk_summary_documents_summary_id', 'summary_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summary_documents_summary_id_fkey'), 'summary_documents', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('summary_documents_document_id_fkey'), 'summary_documents', 'documents', ['document_id'], ['id'])
    op.drop_constraint('fk_summaries_user_id', 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_user_id_fkey'), 'summaries', 'users', ['user_id'], ['id'])
    op.drop_column('summaries', 'deleted_documents_info')
    op.drop_constraint('fk_study_spaces_user_id', 'study_spaces', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('study_spaces_user_id_fkey'), 'study_spaces', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_study_space_summaries_study_space_id', 'study_space_summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint('fk_study_space_summaries_summary_id', 'study_space_summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('study_space_summaries_summary_id_fkey'), 'study_space_summaries', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('study_space_summaries_study_space_id_fkey'), 'study_space_summaries', 'study_spaces', ['study_space_id'], ['id'])
    op.drop_constraint('fk_study_space_documents_document_id', 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint('fk_study_space_documents_study_space_id', 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('study_space_documents_document_id_fkey'), 'study_space_documents', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('study_space_documents_study_space_id_fkey'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'])
    op.drop_constraint('fk_quizzes_study_space_id', 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint('fk_quizzes_summary_id', 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint('fk_quizzes_user_id', 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_study_space_id_fkey'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'])
    op.create_foreign_key(op.f('quizzes_summary_id_fkey'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'])
    op.drop_column('quizzes', 'source_summary_ids')
    op.drop_column('quizzes', 'source_document_ids')
    op.drop_constraint('fk_quiz_attempts_user_id', 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint('fk_quiz_attempts_quiz_id', 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.drop_column('quiz_attempts', 'study_space_snapshot')
    op.drop_column('quiz_attempts', 'quiz_snapshot')
    op.drop_constraint('fk_documents_user_id', 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
