"""first

Revision ID: cad94131dda7
Revises:
Create Date: 2025-12-01 02:09:48.609167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = 'cad94131dda7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('max_documents_per_summary', sa.Integer(), nullable=False),
    sa.Column('max_file_size_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_users_email'), 'users', ['email'], unique=True, schema='studyforge')
    op.create_index(op.f('ix_studyforge_users_username'), 'users', ['username'], unique=True, schema='studyforge')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_content', sa.LargeBinary(), nullable=False),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], name=op.f('fk_documents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_documents_user_id'), 'documents', ['user_id'], unique=False, schema='studyforge')
    op.create_table('study_spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], name=op.f('fk_study_spaces_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_spaces')),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_study_spaces_user_id'), 'study_spaces', ['user_id'], unique=False, schema='studyforge')
    op.create_table('study_space_documents',
    sa.Column('study_space_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['studyforge.documents.id'], name=op.f('fk_study_space_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['study_space_id'], ['studyforge.study_spaces.id'], name=op.f('fk_study_space_documents_study_space_id_study_spaces')),
    sa.PrimaryKeyConstraint('study_space_id', 'document_id', name=op.f('pk_study_space_documents')),
    schema='studyforge'
    )
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('study_space_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', JSONB(), nullable=False),
    sa.Column('expertise_level', sa.String(length=20), nullable=False),
    sa.Column('topics', JSONB(), nullable=False),
    sa.Column('key_concepts', JSONB(), nullable=False),
    sa.Column('source_document_title', sa.String(length=255), nullable=True),
    sa.Column('source_document_filename', sa.String(length=255), nullable=True),
    sa.Column('document_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['studyforge.documents.id'], name=op.f('fk_summaries_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_space_id'], ['studyforge.study_spaces.id'], name=op.f('fk_summaries_study_space_id_study_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], name=op.f('fk_summaries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summaries')),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_summaries_document_id'), 'summaries', ['document_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_summaries_expertise_level'), 'summaries', ['expertise_level'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_summaries_study_space_id'), 'summaries', ['study_space_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_summaries_user_id'), 'summaries', ['user_id'], unique=False, schema='studyforge')
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('study_space_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('questions', JSONB(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_summary_id', sa.UUID(), nullable=True),
    sa.Column('source_names', JSONB(), nullable=True),
    sa.Column('source_metadata', JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(source_type = 'document' AND source_document_id IS NOT NULL AND source_summary_id IS NULL) OR (source_type = 'summary' AND source_summary_id IS NOT NULL AND source_document_id IS NULL) OR (source_type = 'study_space' AND source_document_id IS NULL AND source_summary_id IS NULL)", name=op.f('ck_quizzes_single_source_type')),
    sa.ForeignKeyConstraint(['source_document_id'], ['studyforge.documents.id'], name=op.f('fk_quizzes_source_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_summary_id'], ['studyforge.summaries.id'], name=op.f('fk_quizzes_source_summary_id_summaries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_space_id'], ['studyforge.study_spaces.id'], name=op.f('fk_quizzes_study_space_id_study_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], name=op.f('fk_quizzes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes')),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_quizzes_source_document_id'), 'quizzes', ['source_document_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_quizzes_source_summary_id'), 'quizzes', ['source_summary_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_quizzes_study_space_id'), 'quizzes', ['study_space_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_quizzes_user_id'), 'quizzes', ['user_id'], unique=False, schema='studyforge')
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('correct_answers', JSONB(), nullable=False),
    sa.Column('user_answers', JSONB(), nullable=False),
    sa.Column('quiz_snapshot', JSONB(), nullable=True),
    sa.Column('study_space_snapshot', JSONB(), nullable=True),
    sa.Column('quiz_title', sa.String(length=255), nullable=False),
    sa.Column('quiz_state', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['studyforge.quizzes.id'], name=op.f('fk_quiz_attempts_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], name=op.f('fk_quiz_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts')),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False, schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studyforge_quiz_attempts_user_id'), table_name='quiz_attempts', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quiz_attempts_quiz_id'), table_name='quiz_attempts', schema='studyforge')
    op.drop_table('quiz_attempts', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quizzes_user_id'), table_name='quizzes', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quizzes_study_space_id'), table_name='quizzes', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quizzes_source_summary_id'), table_name='quizzes', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quizzes_source_document_id'), table_name='quizzes', schema='studyforge')
    op.drop_table('quizzes', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_summaries_user_id'), table_name='summaries', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_summaries_study_space_id'), table_name='summaries', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_summaries_expertise_level'), table_name='summaries', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_summaries_document_id'), table_name='summaries', schema='studyforge')
    op.drop_table('summaries', schema='studyforge')
    op.drop_table('study_space_documents', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_study_spaces_user_id'), table_name='study_spaces', schema='studyforge')
    op.drop_table('study_spaces', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_documents_user_id'), table_name='documents', schema='studyforge')
    op.drop_table('documents', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_users_username'), table_name='users', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_users_email'), table_name='users', schema='studyforge')
    op.drop_table('users', schema='studyforge')
    # ### end Alembic commands ###
