"""Crear tablas iniciales

Revision ID: ce90f65e4d62
Revises: 
Create Date: 2025-11-19 00:38:17.779822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce90f65e4d62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_users_email'), 'users', ['email'], unique=True, schema='studyforge')
    op.create_index(op.f('ix_studyforge_users_username'), 'users', ['username'], unique=True, schema='studyforge')
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expertise_level', sa.Enum('BASICO', 'MEDIO', 'AVANZADO', name='expertiselevel'), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_summaries_expertise_level'), 'summaries', ['expertise_level'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_summaries_user_id'), 'summaries', ['user_id'], unique=False, schema='studyforge')
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['studyforge.summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_quizzes_summary_id'), 'quizzes', ['summary_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_quizzes_user_id'), 'quizzes', ['user_id'], unique=False, schema='studyforge')
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.Column('option_c', sa.String(length=500), nullable=False),
    sa.Column('option_d', sa.String(length=500), nullable=False),
    sa.Column('correct_option', sa.Enum('A', 'B', 'C', 'D', name='optionenum'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['studyforge.quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_questions_quiz_id'), 'questions', ['quiz_id'], unique=False, schema='studyforge')
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['studyforge.quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False, schema='studyforge')
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.Enum('A', 'B', 'C', 'D', name='optionenum'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['studyforge.quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['studyforge.questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_answers_attempt_id'), 'answers', ['attempt_id'], unique=False, schema='studyforge')
    op.create_index(op.f('ix_studyforge_answers_question_id'), 'answers', ['question_id'], unique=False, schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studyforge_answers_question_id'), table_name='answers', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_answers_attempt_id'), table_name='answers', schema='studyforge')
    op.drop_table('answers', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quiz_attempts_user_id'), table_name='quiz_attempts', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quiz_attempts_quiz_id'), table_name='quiz_attempts', schema='studyforge')
    op.drop_table('quiz_attempts', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_questions_quiz_id'), table_name='questions', schema='studyforge')
    op.drop_table('questions', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quizzes_user_id'), table_name='quizzes', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_quizzes_summary_id'), table_name='quizzes', schema='studyforge')
    op.drop_table('quizzes', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_summaries_user_id'), table_name='summaries', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_summaries_expertise_level'), table_name='summaries', schema='studyforge')
    op.drop_table('summaries', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_users_username'), table_name='users', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_users_email'), table_name='users', schema='studyforge')
    op.drop_table('users', schema='studyforge')
    # ### end Alembic commands ###
