"""Remove study_space_summaries junction table (Summary now 1-N with StudySpace)

Revision ID: cfc73fc0a3f8
Revises: 1e432b42e2f8
Create Date: 2025-11-28 15:26:01.282151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc73fc0a3f8'
down_revision: Union[str, Sequence[str], None] = '1e432b42e2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_space_summaries', schema='studyforge')
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.alter_column('study_spaces', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_summary_documents_summary_id_summaries'), 'summary_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_summary_documents_document_id_documents'), 'summary_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summary_documents_document_id_documents'), 'summary_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_summary_documents_summary_id_summaries'), 'summary_documents', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_summary_documents_summary_id_summaries'), 'summary_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summary_documents_document_id_documents'), 'summary_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summary_documents_document_id_documents'), 'summary_documents', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('fk_summary_documents_summary_id_summaries'), 'summary_documents', 'summaries', ['summary_id'], ['id'])
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'])
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'])
    op.alter_column('study_spaces', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'])
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'])
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'])
    op.create_table('study_space_summaries',
    sa.Column('study_space_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['study_space_id'], ['study_spaces.id'], name=op.f('fk_study_space_summaries_study_space_id_study_spaces')),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], name=op.f('fk_study_space_summaries_summary_id_summaries')),
    sa.PrimaryKeyConstraint('study_space_id', 'summary_id', name=op.f('pk_study_space_summaries')),
    schema='studyforge'
    )
    # ### end Alembic commands ###
