"""restructure_summary_table_to_plan_spec

Revision ID: da3f1a1fb344
Revises: cfc73fc0a3f8
Create Date: 2025-11-28 20:09:50.050900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da3f1a1fb344'
down_revision: Union[str, Sequence[str], None] = 'cfc73fc0a3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_documents')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.alter_column('study_spaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('study_spaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.add_column('summaries', sa.Column('source_document_title', sa.String(length=255), nullable=True))
    op.add_column('summaries', sa.Column('source_document_filename', sa.String(length=255), nullable=True))
    op.alter_column('summaries', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('summaries', 'document_state',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_column('summaries', 'document_file_name')
    op.drop_column('summaries', 'study_space_color')
    op.drop_column('summaries', 'study_space_name')
    op.drop_column('summaries', 'document_title')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('summaries', sa.Column('document_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('summaries', sa.Column('study_space_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('summaries', sa.Column('study_space_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.add_column('summaries', sa.Column('document_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_summaries_user_id_users'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_document_id_documents'), 'summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_study_space_id_study_spaces'), 'summaries', 'study_spaces', ['study_space_id'], ['id'])
    op.create_foreign_key(op.f('fk_summaries_document_id_documents'), 'summaries', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('fk_summaries_user_id_users'), 'summaries', 'users', ['user_id'], ['id'])
    op.alter_column('summaries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('summaries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('summaries', 'document_state',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('summaries', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('summaries', 'source_document_filename')
    op.drop_column('summaries', 'source_document_title')
    op.drop_constraint(op.f('fk_study_spaces_user_id_users'), 'study_spaces', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id_users'), 'study_spaces', 'users', ['user_id'], ['id'])
    op.alter_column('study_spaces', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('study_spaces', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id_study_spaces'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'])
    op.create_foreign_key(op.f('fk_study_space_documents_document_id_documents'), 'study_space_documents', 'documents', ['document_id'], ['id'])
    op.drop_constraint(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_user_id_users'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_study_space_id_study_spaces'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_summary_id_summaries'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_user_id_users'), 'quizzes', 'users', ['user_id'], ['id'])
    op.alter_column('quizzes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id_users'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_documents_user_id_users'), 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id_users'), 'documents', 'users', ['user_id'], ['id'])
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('summary_documents',
    sa.Column('summary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_summary_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], name=op.f('fk_summary_documents_summary_id_summaries')),
    sa.PrimaryKeyConstraint('summary_id', 'document_id', name=op.f('summary_documents_pkey'))
    )
    # ### end Alembic commands ###
