"""Actualización tablas document, summary_documents, users y sumaries

Revision ID: f4f083c1d0fc
Revises: ce90f65e4d62
Create Date: 2025-11-19 16:45:36.652786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f083c1d0fc'
down_revision: Union[str, Sequence[str], None] = 'ce90f65e4d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_content', sa.LargeBinary(), nullable=False),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['studyforge.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='studyforge'
    )
    op.create_index(op.f('ix_studyforge_documents_user_id'), 'documents', ['user_id'], unique=False, schema='studyforge')
    op.create_table('summary_documents',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['studyforge.documents.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['studyforge.summaries.id'], ),
    sa.PrimaryKeyConstraint('summary_id', 'document_id'),
    schema='studyforge'
    )
    op.drop_constraint(op.f('answers_attempt_id_fkey'), 'answers', type_='foreignkey')
    op.drop_constraint(op.f('answers_question_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'quiz_attempts', ['attempt_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('questions_quiz_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('quizzes_summary_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('summaries_user_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_column('summaries', 'original_file_type')
    op.drop_column('summaries', 'original_file_name')
    op.add_column('users', sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('max_documents_per_summary', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('max_file_size_bytes', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_file_size_bytes')
    op.drop_column('users', 'max_documents_per_summary')
    op.drop_column('users', 'storage_used_bytes')
    op.drop_column('users', 'storage_quota_bytes')
    op.add_column('summaries', sa.Column('original_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('summaries', sa.Column('original_file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_user_id_fkey'), 'summaries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quizzes_summary_id_fkey'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'questions', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('questions_quiz_id_fkey'), 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'answers', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'answers', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('answers_question_id_fkey'), 'answers', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('answers_attempt_id_fkey'), 'answers', 'quiz_attempts', ['attempt_id'], ['id'])
    op.drop_table('summary_documents', schema='studyforge')
    op.drop_index(op.f('ix_studyforge_documents_user_id'), table_name='documents', schema='studyforge')
    op.drop_table('documents', schema='studyforge')
    # ### end Alembic commands ###
