"""remove_topic_tracking

Revision ID: fbdf6cca3f23
Revises: c9fc36cea810
Create Date: 2025-11-26 22:53:09.572301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdf6cca3f23'
down_revision: Union[str, Sequence[str], None] = 'c9fc36cea810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_user_id'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_quiz_attempts_user_id'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_attempts_quiz_id'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_quizzes_user_id'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_study_space_id'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_summary_id'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quizzes', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')

    # Clean quiz_snapshot.topic from existing quiz_attempts
    op.execute("""
        UPDATE studyforge.quiz_attempts
        SET quiz_snapshot = quiz_snapshot - 'topic'
        WHERE quiz_snapshot ? 'topic'
    """)

    op.drop_column('quizzes', 'topic', schema='studyforge')
    op.drop_constraint(op.f('fk_study_space_documents_document_id'), 'study_space_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_documents_study_space_id'), 'study_space_documents', type_='foreignkey')
    op.create_foreign_key(None, 'study_space_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_study_space_summaries_study_space_id'), 'study_space_summaries', type_='foreignkey')
    op.drop_constraint(op.f('fk_study_space_summaries_summary_id'), 'study_space_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'study_space_summaries', 'study_spaces', ['study_space_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'study_space_summaries', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_study_spaces_user_id'), 'study_spaces', type_='foreignkey')
    op.create_foreign_key(None, 'study_spaces', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_summaries_user_id'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'users', ['user_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.drop_constraint(op.f('fk_summary_documents_document_id'), 'summary_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_summary_documents_summary_id'), 'summary_documents', type_='foreignkey')
    op.create_foreign_key(None, 'summary_documents', 'documents', ['document_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    op.create_foreign_key(None, 'summary_documents', 'summaries', ['summary_id'], ['id'], source_schema='studyforge', referent_schema='studyforge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summary_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'summary_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summary_documents_summary_id'), 'summary_documents', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('fk_summary_documents_document_id'), 'summary_documents', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_summaries_user_id'), 'summaries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'study_spaces', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_spaces_user_id'), 'study_spaces', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'study_space_summaries', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'study_space_summaries', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_summaries_summary_id'), 'study_space_summaries', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('fk_study_space_summaries_study_space_id'), 'study_space_summaries', 'study_spaces', ['study_space_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'study_space_documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_study_space_documents_study_space_id'), 'study_space_documents', 'study_spaces', ['study_space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_study_space_documents_document_id'), 'study_space_documents', 'documents', ['document_id'], ['id'])
    op.add_column('quizzes', sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quizzes_summary_id'), 'quizzes', 'summaries', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('fk_quizzes_study_space_id'), 'quizzes', 'study_spaces', ['study_space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_quizzes_user_id'), 'quizzes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_attempts_quiz_id'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('fk_quiz_attempts_user_id'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'documents', schema='studyforge', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_user_id'), 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
